openapi: 3.0.0
info:
  title: Faculty API
  version: 1.0.0
paths:
  /lecturers:
    get:
      summary: Retrieve a list of all lecturers
      responses:
        '200':
          description: A list of all lecturers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
    post:
      summary: Add a new lecturer
      requestBody:
        description: New lecturer details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewLecturer'
      responses:
        '201':
          description: Successfully added a new lecturer
  /lecturers/{staffNumber}:
    get:
      summary: Retrieve details of a specific lecturer
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the specific lecturer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
    put:
      summary: Update an existing lecturer's information
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Updated lecturer details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        '200':
          description: Successfully updated lecturer information
    delete:
      summary: Delete a lecturer's record by their staff number
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted the lecturer
  /lecturers/courses/{courseCode}:
    get:
      summary: Retrieve all lecturers that teach a certain course
      parameters:
        - name: courseCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of lecturers teaching the course
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
  /lecturers/offices/{officeNumber}:
    get:
      summary: Retrieve all lecturers that sit in the same office
      parameters:
        - name: officeNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of lecturers in the same office
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
components:
  schemas:
    NewLecturer:
      type: object
      properties:
        staffNumber:
          type: string
        officeNumber:
          type: string
        staffName:
          type: string
        title:
          type: string
        courses:
          type: array
          items:
            type: string
    Lecturer:
      type: object
      properties:
        staffNumber:
          type: string
        officeNumber:
          type: string
        staffName:
          type: string
        title:
          type: string
        courses:
          type: array
          items:
            type: string
